### PR TITLE
changed background

### PR DESCRIPTION
**Pull request by aoalaka**
@ydaniju,  pls help review and approve.

### CODE REVIEW

**Comment by aoalaka** [comment]
I'm still expecting your response sir @ydaniju

**Comment by ydaniju** [comment]
I'm on my way home from the hospital.

On Feb 9, 2018 11:38 AM, "Abdulquadri O. Alaka" <notifications@github.com> wrote:

I'm still expecting your response sir @ydaniju<https://github.com/ydaniju>

**Comment by aoalaka** [comment]
Hospital? Hope no problem sir?

**Comment by ydaniju** [comment]
No problem. Took my grandmother for eye checkup

**Pull request merged**
